
// AUTH ACTION TYPES
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

// GROUP ACTION TYPES
export const FETCH_GROUP_INFO = 'FETCH_GROUP_INFO';
export const FETCH_GROUP_DETAIL_INFO = 'FETCH_GROUP_DETAIL_INFO';
export const CREATE_GROUP = 'CREATE_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';

// PROJECT ACTION TYPES
export const FETCH_PROJECT_INFO = 'FETCH_PROJECT_INFO';
export const FETCH_PROJECT_DETAIL_INFO = 'FETCH_PROJECT_DETAIL_INFO';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
